'on': push
jobs:
  build:
    runs-on: ubuntu-latest
    container: 'node:20'
    steps:
      - run: node --version
      - run: npm --version
      - uses: actions/checkout@v4
      - run : npm install
      - run : node app.js